import sbt._
import sbt.util.Logger
import scala.sys.process._

/** Builds the native tree-sitter libraries the Treesitter frontend loads.
  */
object TreeSitter {

  case class Grammar(name: String, repo: String, ref: String)

  val core = Grammar("tree-sitter", "https://github.com/tree-sitter/tree-sitter", "v0.25.10")

  val grammars = Seq(
    Grammar("c",      "https://github.com/tree-sitter/tree-sitter-c",     "v0.24.1"),
    Grammar("scala",  "https://github.com/tree-sitter/tree-sitter-scala", "v0.24.0"),
    Grammar("fpcore", "https://github.com/agilot/tree-sitter-fpcore",     "v0.1.1")
  )

  /** Resolves OS specifics **/
  private val (osName, extension, sharedFlag) =
    System.getProperty("os.name").toLowerCase match {
      case os if os.contains("mac") || os.contains("darwin") => ("darwin", "dylib", "-dynamiclib")
      case os if os.contains("win")                          => ("windows", "dll", "-shared")
      case _                                                 => ("linux", "so", "-shared")
    }

  /** Resolves architecture specifics. */
  private val arch = System.getProperty("os.arch").toLowerCase match {
    case "amd64" | "x86_64"  => "x86_64"
    case "aarch64" | "arm64" => "aarch64"
    case other               => other
  }

  val platform = s"$osName-$arch"

  private def sanitize(ref: String): String = ref.replaceAll("[^A-Za-z0-9.]+", "-")

  val libraryNames: Map[String, String] =
    ((core.name -> s"lib${core.name}-${sanitize(core.ref)}-$platform.$extension") +:
      grammars.map(g =>
        s"tree-sitter-${g.name}" ->
          s"libtree-sitter-${g.name}-${sanitize(g.ref)}-$platform.$extension")
    ).toMap

  /** Clones a git repository if it is not already present **/
  private def checkout(dir: File, repo: String, ref: String, log: Logger): File = {
    if (!(dir / ".git").exists) {
      IO.delete(dir)                        // clears a half-finished earlier clone
      IO.createDirectory(dir.getParentFile)
      log.info(s"Fetching $repo @ $ref")
      if (Seq("git", "-c", "advice.detachedHead=false",
              "clone", "--depth", "1", "--branch", ref, "--quiet", repo, dir.getPath).! != 0)
        sys.error(s"could not clone $repo @ $ref")
    }
    dir
  }

  /** Compiles a library from C/C++ sources. **/
  private def compileLib(out: File, sources: Seq[File], include: File, driver: String,
                         log: Logger): File = {
    log.info(s"Building ${out.getName}")
    // -I because parser.c includes tree_sitter/parser.h from its own src/.
    val cmd = Seq(driver, sharedFlag, "-fPIC", "-O2", "-I", include.getPath) ++
      sources.map(_.getPath) ++ Seq("-o", out.getPath)
    if (cmd.! != 0) sys.error(s"could not build ${out.getName}")
    out
  }

  /** Checks that the library is not already present, otherwise builds it. **/
  private def ensure(out: File)(build: => File): File = if (out.exists) out else build

  def buildAll(libDir: File, log: Logger): Seq[File] = {
    val cacheDir = libDir / ".grammars"

    val coreLib = {
      val out = libDir / libraryNames(core.name)
      ensure(out) {
        val dir = checkout(cacheDir / core.name, core.repo, core.ref, log)
        compileLib(
          out,
          Seq(dir / "lib" / "src" / "lib.c"),   // amalgamation: includes the rest
          dir / "lib" / "include",
          "cc",
          log)
      }
    }

    val parsers = grammars.map { g =>
      val out = libDir / libraryNames(s"tree-sitter-${g.name}")
      ensure(out) {
        val src = checkout(cacheDir / s"tree-sitter-${g.name}", g.repo, g.ref, log) / "src"
        // Grammars needing context-sensitive lexing ship a hand-written scanner;
        // tree-sitter-scala has one for indentation. A C++ one needs the C++ driver.
        val scanner = Seq(src / "scanner.c", src / "scanner.cc").filter(_.exists)
        val driver = if (scanner.exists(_.getName.endsWith(".cc"))) "c++" else "cc"
        compileLib(out, (src / "parser.c") +: scanner, src, driver, log)
      }
    }

    coreLib +: parsers
  }

  /** Emits the library names as Scala, so the frontend never tries to guess them. */
  def generateBuildInfo(sourceManaged: File): File = {
    val out = sourceManaged / "daisy" / "frontend" / "TreesitterBuildInfo.scala"
    val entries = libraryNames.toSeq.sorted
      .map { case (key, file) => s"""    "$key" -> "$file"""" }
      .mkString(",\n")

    val content =
      s"""|// Generated by project/TreeSitter.scala. Do not edit.
          |package daisy.frontend
          |
          |private[frontend] object TreesitterBuildInfo {
          |  val platform: String = "$platform"
          |
          |  val libraries: Map[String, String] = Map(
          |$entries
          |  )
          |}
          |""".stripMargin

    if (!out.exists || IO.read(out) != content) IO.write(out, content)
    out
  }
}
